name: Node.js Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm run build


  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build:all
      - name: Git Commit + Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version patch --no-git-tag-version
          git commit -am "chore: version bump"
          git tag v$(node -p "require('./package.json').version")
          git push && git push --tags
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
