name: Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - run: npm test
      - run: npm run build:all

      - name: Release with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
